const student = [
    {
        id          :    1,
        name        :   'Jweel',
        rool        :   25,
        reg         :   365562544154148,
        class       :   362,
        loocation   :   'Dhaka',

        bangla      :   80,
        agreecuncer :   40,
        english     :   96,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   80,
    },
    {
        id          :    2,
        name        :   'Achem',
        rool        :   30,
        reg         :   155562543040148,
        class       :   8,
        loocation   :   'Bhola',

        bangla      :   50,
        agreecuncer :   90,
        english     :   88,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   78,
    },
    {
        id          :    3,
        name        :   'Rana',
        rool        :   40,
        reg         :   225562544542248,
        class       :   9,
        loocation   :   'Khulna',

        bangla      :   98,
        agreecuncer :   98,
        english     :   63,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   89,
    },
    {
        id          :    4,
        name        :   'Sweety',
        rool        :   21,
        reg         :   95562542948,
        class       :   7,
        loocation   :   'Kurigram',

        bangla      :   75,
        agreecuncer :   60,
        english     :   48,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   32,
    },
    {
        id          :    5,
        name        :   'Rayhan',
        rool        :   41,
        reg         :   75562544748,
        class       :   8,
        loocation   :   'Rangpur',

        bangla      :   93,
        agreecuncer :   45,
        english     :   69,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   30,
    },
    {
        id          :    6,
        name        :   'ashraf',
        rool        :   23,
        reg         :   855625423148,
        class       :   8,
        loocation   :   'Dinajpur',

        bangla      :   96,
        agreecuncer :   46,
        english     :   78,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   45,
    },
    {
        id          :    7,
        name        :   'Arafat',
        rool        :   62,
        reg         :   2555625465148,
        class       :   7,
        loocation   :   'Khulna',

        bangla      :   50,
        agreecuncer :   50,
        english     :   69,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   63,
    },
    {
        id          :    8,
        name        :   'Mahi',
        rool        :   29,
        reg         :   7355625429148,
        class       :   9,
        loocation   :   'Savar',

        bangla      :   48,
        agreecuncer :   66,
        english     :   78,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   48,
    },
    {
        id          :    9,
        name        :   'Nahid',
        rool        :   52,
        reg         :   955625452148,
        class       :   8,
        loocation   :   'Gazipur',

        bangla      :   59,
        agreecuncer :   97,
        english     :   36,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   78,
    },
    {
        id          :    10,
        name        :   'Sabbir',
        rool        :   25,
        reg         :   855625465148,
        class       :   7,
        loocation   :   'CGT',

        bangla      :   77,
        agreecuncer :   89,
        english     :   36,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   79,
    },

]